- hosts: all
  become: true
  tasks:
    - name: Create superusers group
      group:
        name: superusers
        state: present

    - name: Add user2 and user3 to superusers group
      user:
        name: "{{ item }}"
        groups: superusers
      with_items:
        - user2
        - user3

    - name: Allow superusers to become root
      lineinfile:
        path: /etc/sudoers
        line: "%superusers ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"